name: Sync Google Sheets to JSON

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:
  
jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch Google Sheets data
      run: |
        # Fetch all data from Google Sheets and save it to wishes.json
        curl -X GET "https://sheets.googleapis.com/v4/spreadsheets/${{ secrets.SPREADSHEET_ID }}/values/Wishes!A:D?key=${{ secrets.GOOGLE_API_KEY }}" -o wishes.json

        # Filter only the records with "Approved" status (without trim)
        jq '[.values[] | select(.[3] == "Approved")]' wishes.json > wishes.json

        # Output the filtered data for debugging
        echo "Filtered wishes:"
        cat wishes.json
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add wishes.json
        git commit -m "Update wishes JSON with only approved wishes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
